USE [master]
GO

/****** Object:  Database [StudyTrickDB]    Script Date: 10-03-2025 11:54:25 ******/
CREATE DATABASE [StudyTrickDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'StudyTrickDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS01\MSSQL\DATA\StudyTrickDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'StudyTrickDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS01\MSSQL\DATA\StudyTrickDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [StudyTrickDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [StudyTrickDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [StudyTrickDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [StudyTrickDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [StudyTrickDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [StudyTrickDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [StudyTrickDB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [StudyTrickDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [StudyTrickDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [StudyTrickDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [StudyTrickDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [StudyTrickDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [StudyTrickDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [StudyTrickDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [StudyTrickDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [StudyTrickDB] SET  DISABLE_BROKER 
GO

ALTER DATABASE [StudyTrickDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [StudyTrickDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [StudyTrickDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [StudyTrickDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [StudyTrickDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [StudyTrickDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [StudyTrickDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [StudyTrickDB] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [StudyTrickDB] SET  MULTI_USER 
GO

ALTER DATABASE [StudyTrickDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [StudyTrickDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [StudyTrickDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [StudyTrickDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [StudyTrickDB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [StudyTrickDB] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [StudyTrickDB] SET QUERY_STORE = OFF
GO

ALTER DATABASE [StudyTrickDB] SET  READ_WRITE 
GO

